### PR TITLE
Add Coveralls support

### PR DESCRIPTION
**Pull request by philipmw**
100% coverage!

### CODE REVIEW

**Comment by bhuga** [comment]
Looks like travis doesn't like this on 1.8.7, which I'm cool to :fire: from travis.yml.

**Comment by bhuga** [comment]
Do we need to add a webhook for this repo for coveralls? Can you link me to what needs to happen?

**Comment by bhuga** [comment]
And in case it's not clear, :+1: :grinning:

**Comment by philipmw** [comment]
Updated .travis.yml. I added the web hook on coveralls.io.

**Comment by philipmw** [comment]
@bhuga, do you want time to review my three PRs, or should I pull them in?

**Comment by bhuga** [comment]
@philipmw all 3 are about green statuses, so if statuses are green, :+1:. Tough week for me to look at them.

**Pull request merged**
